### ISSUE TITLE
SDK creating repeated unnecessary WETH approval transactions

### ISSUE THREAD

**Issue by 0xfoobar** [ProjectOpenSea/opensea-js#107]
I have approved infinite WETH for the OpenSea contract, and had successful bids go through.

Yet yesterday (around 12 hours ago), the OpenSea SDK sent another WETH approval transaction, and then another three hours later. I shut down all programs running with it for fear of losing more gas, so I don't know if this would have recurred more frequently.

This is a new and sporadic occurrence, but deeply worrying - if I can't trust the SDK with my account without worrying about it spending all my ETH on unnecessary gas, then I can't really use it at all.

**Comment by oguzhanbulut** [comment]
Does this problem still occur?

**Comment by esteban-OpenSea** [comment]
Hello, just wanted to follow up on this. Are you still having issues with this? If so, please provide more details if possible. Thanks!

**Comment by 0xfoobar** [comment]
First, this issue is 10 months old. Not sure what details you would expect me to have now.

Second, I'm not going to go risk a ton of real-life WETH (that will get lost forever due to SDK creator negligence) to try it out again.

**Comment by arishabh** [comment]
I am also receiving the exact same issue. I randomly get approved weth transactions when I am making offers on nfts @esteban-OpenSea

**Comment by arishabh** [comment]
More info:
I never received this issue before, but I changed my wallet to a different one and since then I have been getting this issue. It was a brand new wallet. I tried doing the one time Opensea seller setup, but it's still giving me this issue. Not sure if it has something to do with the wallet or a different bug. Also, I tried changing the RPC network and the frequency of the "Approved WETH" transactions reduced, but were still there @esteban-OpenSea
