### ISSUE TITLE
Fetch Users

### ISSUE THREAD

**Issue by Sandeeprao69** [ProjectOpenSea/opensea-js#111]
Is There a way to show raning just like shown in https://opensea.io/rankings
Also is there way to fetch top sellers

**Comment by esteban-OpenSea** [comment]
Hello, although there is no `/rankings` endpoint. You can still search several assets and collections and customize your search. I encourage you to look over our [documentation](https://docs.opensea.io/reference/api-overview). I will go ahead and close this since this isn't a specific issue/bug with opensea-js
