### ISSUE TITLE
OpenSea Testnets - Unsupported operand type(s) for /: 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by onlit** [ProjectOpenSea/opensea-js#122]
I am working on buying asset script using opensea js. I followed the docs and got it working on Mainnet. But when I change my Network and MetaMask to Rinkeby. I get an error: `Not found: no matching order found`

So for testing I tried to buy Rinkeby assets directly from opensea testnets website. And the first thing I noticed when I clicked Buy Now. We have a few different options. I had to click Convert your ETH and Unlock Currency, which was successful. MetaMask showed up and asked me to allow a few things and I did.

And finally, when I clicked on the Sign, MetaMask showed up again asking me to Sign or Reject. I click Sign and I get an error: `unsupported operand types for /: 'NoneType' and 'NoneType'`

Asset URL: https://testnets.opensea.io/assets/0x7dca125b1e805dc88814aed7ccc810f677d3e1db/25

**Comment by ChangoMan** [comment]
Hello, I ran into a similar issue when trying to buy an asset with WETH on the testnet. Not sure if this is helpful, but instead of trying to buy an asset being sold in WETH, I just looked up assets being sold in normal ETH. Seems like buying an asset in normal ETH doesn't require the Unlock Currency, and therefor no errors for me.

**Comment by esteban-OpenSea** [comment]
Hello, just wanted to check in with everyone. Are you still having this issue?

**Comment by esteban-OpenSea** [comment]
Checking in again, are you still having this issue?
