### ISSUE TITLE
How do I get an API key?

### ISSUE THREAD

**Issue by edcubepriv** [ProjectOpenSea/opensea-js#246]
Hey @michael-cohen-eth,

how long does it usually take to review an API key request?
We sent ours for nftnerds.ai through https://docs.opensea.io/reference/request-an-api-key.

**Comment by artyomLisovskij** [comment]
they don't reposne for a couple of monthes for me too.

**Comment by derwaldgeist** [comment]
Did you eventually got your key? If they take that long, we'll look into other marketplaces.

**Comment by esteban-OpenSea** [comment]
You apply `[here](https://docs.opensea.io/reference/request-an-api-key)`. API requests can take up to (5) business days to be processed. If yours hasn’t, it’s likely because it didn’t fit out criteria for issuing one.
 
In order to be approved, you need:

- A signed message using your wallet address (please use a tool such as [MyCrypto](https://app.mycrypto.com/sign-message))
- Your email and project name
- A non-zero amount of ETH in your wallet
- Once you have all of this, please head back to our request form [here](https://docs.opensea.io/reference/request-an-api-key) to request another

**Comment by Krybskytten** [comment]
@esteban-OpenSea I've filled out multiple ones which to my knowledge should be correct. The instructions have been carefully followed by me on all of my requests, however, still no answer. Is there an example of this somewhere with real values, such as a real email, real eth address etc? 

Thank you in advance.
