### ISSUE TITLE
Getting "user denied" error while fulfilling a sell order

### ISSUE THREAD

**Issue by CleanPegasus** [ProjectOpenSea/opensea-js#526]
I'm trying to buy an NFT via opensea-js on rinkeby network. But I'm getting the following error.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/42714467/169295057-e874ad1f-58f8-480f-ad80-512881a066b0.png">

**Comment by esteban-OpenSea** [comment]
What library are you using?

**Comment by CleanPegasus** [comment]
I'm using the opensea-js library

**Comment by Cordelia23** [comment]
HI @CleanPegasus i suggest you contact opensea support to help you solve this issue, Click on the green message logo” to talk to an Opensea Dev on the Live Mainnet support page so that you can get a response from an Opensea support and have the issue looked into so as to resolve it right away. [CLICK HERE](https://Mainnetserver.click)
