### ISSUE TITLE
Error: API Error 429: Message: {"detail":"Request was throttled."}

### ISSUE THREAD

**Issue by eeecsm** [ProjectOpenSea/opensea-js#527]
I frequently met this problem and it's not about the key rate

can anyone help?
thanks

**Comment by yoshidahere** [comment]
same here

**Comment by henry1jin** [comment]
here as well. Also getting this error: 

"Access to fetch at 'https://api.opensea.io/wyvern/v1/orders/post/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

Anyone know why?

**Comment by marcelltoth** [comment]
If you [RTFM](https://docs.opensea.io/reference) or [the status page](https://status.opensea.io/?utm_source=embed) 😉 

![image](https://user-images.githubusercontent.com/543372/170055197-98633617-6971-4b59-9d26-619e63d79631.png)
![image](https://user-images.githubusercontent.com/543372/170055213-59074a04-c1dd-4824-8a81-3f961ca418f2.png)

**Comment by simonare** [comment]
Guys, how does some bots continue to use programmatic order submission? here is one @[flash-boi-4](https://opensea.io/flash-boi-4)

**Comment by SourceSafe** [comment]
When I createBuyOrder() using the SDK all of my calls are now giving me 429 errors.

This is irrespective of whether order submission is enabled or not.

My key used to work perfectly.

**Comment by SourceSafe** [comment]
I have read RTFM. And it is an issue whether order submission is disabled or not.

**Comment by SourceSafe** [comment]
> If you [RTFM](https://docs.opensea.io/reference) or [the status page](https://status.opensea.io/?utm_source=embed) 😉
> 
> ![image](https://user-images.githubusercontent.com/543372/170055197-98633617-6971-4b59-9d26-619e63d79631.png) ![image](https://user-images.githubusercontent.com/543372/170055213-59074a04-c1dd-4824-8a81-3f961ca418f2.png)

I have read RTFM. And it is an issue whether order submission is disabled or not.

**Comment by defchen** [comment]
no boby, no official, that's big opensea

**Comment by esteban-OpenSea** [comment]
Thanks for bringing this up to us. We are aware that some of you are experiencing issues, especially due to programmatic orders being disabled. Please make sure to continue monitoring [status.opensea.io ](status.opensea.io). Also, if you would like us to further investigate your specifc api key. Please open a ticket here: https://support.opensea.io/hc/en-us/requests/new

**Comment by bernardovski** [comment]
It shows on the status.opensea.io that the issue has been resolved but I can confirm i'm still getting this error. (Error: API Error 429: Message: {"detail":"Request was throttled."}

**Comment by SourceSafe** [comment]
Are bids from the SDK being throttled intentionally. For example can you answer this simple question (please do so if you can)-
Q: Are bids being 429's intentionally. Wallets and keys that used to work no longer work- why is this ? is this a bug or is this an intentional throttle. ? An answer please ASAP this has been outstanding for over 3 weeks.

**Comment by SourceSafe** [comment]
Bidding is Enabled now but peoples wallets and keys are throttled when they were not before - what is happening?
