### ISSUE TITLE
Some bots still able to submit orders despit of opensea api system broken down

### ISSUE THREAD

**Issue by marouaneroussi** [ProjectOpenSea/opensea-js#546]
Hi, can anyone explaine  how some people still making bulk offer like this guy  [https://opensea.io/898989?tab=activity](url) 
despite of opensea api order is disabled.

Thanks

**Comment by marouaneroussi** [comment]
there are a lot of tools like nftinit that still sending bulk offer, i don't now why?

**Comment by esteban-OpenSea** [comment]
Thanks for flagging this! We will look into this.

@simonare , can you send over the link of the question you asked a while ago. That way we can consolidate all the issues related to this.

**Comment by simonare** [comment]
Hey @esteban-OpenSea,

Here it is [Issue #532 ](https://github.com/ProjectOpenSea/opensea-js/issues/532)

please let us know if there is a legit way of doing this.

**Comment by ft1-1** [comment]
> Thanks for flagging this! We will look into this.
> 
> @simonare , can you send over the link of the question you asked a while ago. That way we can consolidate all the issues related to this.

@esteban-OpenSea Can you confirm if the throttling after one bid is a bug or intentional? If this is intentional, can you confirm why this has not impacted all API keys equally?

It's odd that certain individuals have been allowed to create offers via the API with no throttling while others using the same function are throttled. In a lot of cases it's a single individual with multiple wallets who doesn't seem to be throttled (and the speed does not suggest a selenium script is being used). 

Examples of these accounts (these are all the same person):
https://opensea.io/0xE87D840ffD0E62FA903c2ef81A1cDD44268B5432?tab=activity
https://opensea.io/0xF9A0a5F6b9FFA6A0fd2913Abae8fbdffd65Ced03?tab=activity
https://opensea.io/0x77A6e8C6F04D278367E13DD8B4Cce01e6bCe61F4?tab=activity
https://opensea.io/0xF50b62627CB72613f521bCC6256B9d8Bbe85369b?tab=activity
https://opensea.io/0x6b56F772cFd676dc4b8B544E0A8d74198840D1f7?tab=activity
https://opensea.io/0xe132297e7f777dff8595506692b67f3f20a2a98c?tab=activity
https://opensea.io/0x67fcd281e48e4f970b755164bce824a7f647f334?tab=activity
https://opensea.io/0xac8632c709fa0704c19aaa8b99a99dc66b8a3dd5?tab=activity
https://opensea.io/0x7b6c229ec99006fc07c0b88ad26c5fd313ba8b5d?tab=activity

**Comment by ft1-1** [comment]
@esteban-OpenSea 

And further examples owned by the same person.

https://opensea.io/st48ap?tab=activity
https://opensea.io/st49ap?tab=activity
https://opensea.io/st50ap?tab=activity
https://opensea.io/st51ap?tab=activity
https://opensea.io/st52ap?tab=activity
https://opensea.io/st53ap?tab=activity
https://opensea.io/st54ap?tab=activity
https://opensea.io/st55ap?tab=activity
https://opensea.io/st56ap?tab=activity
https://opensea.io/st57ap?tab=activity
https://opensea.io/st58ap?tab=activity
https://opensea.io/st59ap?tab=activity
https://opensea.io/st65ap?tab=activity
https://opensea.io/st64ap?tab=activity
https://opensea.io/st62ap?tab=activity
https://opensea.io/st61ap?tab=activity
https://opensea.io/st60ap?tab=activity

It would be nice to know if either these persons have found a way to send offers that OpenSea cannot throttle, or if they have been excluded from having their keys throttled for whatever reason.

**Comment by coxlabz** [comment]
Facing the same issue. @esteban-OpenSea, is there an ETA on when we can expect an answer?
I know several users are facing this issue while others accounts (or api keys) are not getting throttled.
Thanks

**Comment by ft1-1** [comment]
Any updates on this?
