### ISSUE TITLE
Can't get an API key.

### ISSUE THREAD

**Issue by Easydo888** [ProjectOpenSea/opensea-js#559]
Me and my team requested for an API key TWICE.
Our product is ens.fm

The first request didn't got any response for a month.
I'm afraid that I won't get any response this time too, already several days passed after the new request.
Is there any tip for getting a key?

**Comment by esteban-OpenSea** [comment]
Thanks for letting us know, please go ahead and open up a ticket [here](https://support.opensea.io/hc/en-us/requests/new). Click on "developer help" and then "API Request" from the drop down menu. This will allow us to look into your specific request.

<img width="1577" alt="image" src="https://user-images.githubusercontent.com/99999009/173630033-55420f4b-8e73-4400-9748-ae7469890527.png">

I am going to go ahead and close this since it's not an issue related to the sdk. Please open the ticket and then we can help you. Thanks!
