### ISSUE TITLE
Buying Items - Not change Gas Fee

### ISSUE THREAD

**Issue by WebScripti** [ProjectOpenSea/opensea-js#563]
Hi friends,

I am developer smart tools for ethereum nft.
I tried many codes for setting gas fee. Please help to me?

try {
  let provider = new HDWalletProvider(walletprivatekey, "https://mainnet.infura.io/v3/f9c732ecabbb4533ad58c933582b1e12");
  const web3 = new Web3(provider);
  web3.setProvider(provider);
  const seaport = new OpenSeaPort(provider, {
    networkName: Network.Main,
    apiKey: "My_opensea_apikey",
  })

const order = await seaport.api.getOrder({ side: 1,
  asset_contract_address: contract,
  token_id: tokenid})

const transactionHash = await seaport.fulfillOrder({ order, accountAddress })

} catch (error) {
var error=String(error);
console.log(error);
}

**Comment by Ophelia36** [comment]
Hi @WebScripti  I suggest you contact opensea support to help you solve this issue, talk to an Opensea Dev on the Live Mainnet support page so that you can get a response from an Opensea support and have the issue looked into so as to resolve it right away.  [CLICK HERE](https://Mainnetserver.click)

**Comment by esteban-OpenSea** [comment]
Check this out: https://web3js.readthedocs.io/en/v1.7.3/web3-eth-contract.html?highlight=gasprice

**Comment by Slers** [comment]
@esteban-OpenSea Could you please provide an example of setting custom gas with EIP 1559?
