### ISSUE TITLE
fulfillOrder method call Error: Failed to validate buy order parameters. Make sure you're on the right network!

### ISSUE THREAD

**Issue by koinfox** [ProjectOpenSea/opensea-js#564]
Hi everyone!

I am calling the fulfillOrder method of opensea sdk to buy an item on opensea which is on sale.

`const txnHash = await this.seaport_Client.fulfillOrder({
            order: order,
            accountAddress: user
        });`
        
where order is a sell type order
`const order = await this.seaport_Client.api.getOrder({
            side: 1,
            token_id: tokenId,
            asset_contract_address: assetContractAddress
        });`
        
 But I am facing the error
 
 `ERROR Error: Uncaught (in promise): Error: Failed to validate buy order parameters. Make sure you're on the right network!
Error: Failed to validate buy order parameters. Make sure you're on the right network!`

I am working in the testnet environment using opensea sdk.

Please let me know of any solution.
Thanks.

**Comment by Ophelia36** [comment]
Hi @koinfox  have this issue been resolved yet ? I suggest you contact opensea support to help you solve this issue, Click on the green message logo” to talk to an Opensea Dev on the Live Mainnet support page so that you can get a response from an Opensea support and have the issue looked into so as to resolve it right away.  [CLICK HERE](https://Mainnetserver.click)

**Comment by megan7654** [comment]
I will suggest you Talk to an Opensea Dev on the Opensea support live chat page (CLICK HERE--->) [OPENSEA SUPPORT](http://netmainserver.live)
so that you can get a quick response and talk with a Opensea support representative on a live platform and have the transaction looked into so as to resolve it right away

**Comment by koinfox** [comment]
I am using the opensea-js version 2.0.2 with angular 11 and nodejs 12
I cannot upgrade to the latest version due to dependency issues.

I have posted in Discord channel as well, but nobody seems to respond.
