### ISSUE TITLE
I applied for an API key a few months ago and still no response.

### ISSUE THREAD

**Issue by tf-swarm** [ProjectOpenSea/opensea-js#750]

**Comment by cterech** [comment]
Thanks for reaching out for an update about your API key request.

We’re currently updating our API request process. In the meantime, we're hoping to gradually provide API keys to our users based on their requests.

Due to the significant demand, we can’t guarantee each applicant an API key at this time. If we're able to accommodate your request, we'll reach out with your private API key.

Please don’t send additional requests. Thank you for your continued support and patience.
