### ISSUE TITLE
Transaction failed :( You might have already completed this action. See more on the mainnet at etherscan.io/tx/

### ISSUE THREAD

**Issue by Irantwomiles** [ProjectOpenSea/opensea-js#766]
I am getting an error on the testnet (Goerli) while attempting to fulfillOrder using the SDK. I am modifying the transaction by providing it with a maxFeePerGas, maxPriorityFeePerGas, and a gasLimit property. The gas limit was required, because I kept getting an error specifying that "gas limit could not be calculated, might need to specify manually", and I am providing the other two fields.

The error:

```
                        reject(new Error("Transaction failed :( You might have already completed this action. See more on the mainnet at etherscan.io/tx/".concat(txHash)));
                               ^

Error: Transaction failed :( You might have already completed this action. See more on the mainnet at etherscan.io/tx/0x2c124c0b234572db54ff90249fe5cd281df0cd3304979e9afb682ccb0395378e

```

If you want to check the error on etherscan, make sure you're going to the goerli.etherscan.io/tx/0x2c124c0b234572db54ff90249fe5cd281df0cd3304979e9afb682ccb0395378e link, and not the one in the error.

I am modifying the tx before it is being sent, however I don't change anything in regards to the data itself. 

This is the final transaction object:
 ```
 conduitKey: '0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000',
  offererOperator: '0x1e0049783f008a0085193e00003d00cd54003c71',
  fulfillerOperator: '0x1e0049783f008a0085193e00003d00cd54003c71',
  signer: JsonRpcSigner {
    _isSigner: true,
    provider: Web3Provider {
      _isProvider: true,
      _events: [],
      _emitted: [Object],
      disableCcipRead: false,
      formatter: [Formatter],
      anyNetwork: false,
      _networkPromise: [Promise],
      _maxInternalBlockNumber: -1024,
      _lastBlockNumber: -2,
      _maxFilterBlockRange: 10,
      _pollingInterval: 4000,
      _fastQueryDate: 0,
      connection: [Object],
      _nextId: 42,
      jsonRpcFetchFunc: [Function (anonymous)],
      provider: [HDWalletProvider],
      _eventLoopCache: [Object],
      _network: [Object]
    },
    _address: '0x314Ffdd09543BeFa5080529b306a2D071F760aF8',
    _index: null
  },
  tips: [],
  domain: ''
}
executeCase 7 undefined {
  type: 'exchange',
  transactionMethods: {
    callStatic: [Function: callStatic],
    estimateGas: [Function: estimateGas],
    transact: [Function: transact],
    buildTransaction: [Function: buildTransaction]
  }
} undefined
inside sent: [
  0,
  {
    data: '0xfb0f3ee10000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000008a8e4b1a3d8000000000000000000000000000ccf22bc4ba427151face526731d5694cf1514aac00000000000000000000000000000000000000000000000000000000000000000000000000000000000000005280da1f82649af74fe2d9a3d73fe22f8b0f304b0
0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000
000000000000633c3f2f0000000000000000000000000000000000000000000000000000000063b445c030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007956214511f805e70000007b02230091a7ed012
30072f7006a004d60a8d4e71d599b8104250f00000000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000024000
000000000000000000000000000000000000000000000000000000000002a0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000a26b00c1f0df00300
0390027140000faa7190000000000000000000000000000000000000000000000000000000000000040cad53313637444e1c6c05f09b6ea7965cd5c07605971eac1836b3d1ba2f323a0ba5e412f8ad8b3a73867f0a94dd6bc98b5077e0d5565262d4b1b8f8f018bd6aa',
    to: '0x00000000006c3852cbEf3e08E8dF289169EdE581',
    from: '0x314Ffdd09543BeFa5080529b306a2D071F760aF8',
    value: BigNumber { _hex: '0x8e1bc9bf040000', _isBigNumber: true }
  }
]
inside sent: [
  0,
  {
    data: '0xfb0f3ee10000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000008a8e4b1a3d8000000000000000000000000000ccf22bc4ba427151face526731d5694cf1514aac00000000000000000000000000000000000000000000000000000000000000000000000000000000000000005280da1f82649af74fe2d9a3d73fe22f8b0f304b0
0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000
000000000000633c3f2f0000000000000000000000000000000000000000000000000000000063b445c030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007956214511f805e70000007b02230091a7ed012
30072f7006a004d60a8d4e71d599b8104250f00000000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000024000
000000000000000000000000000000000000000000000000000000000002a0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000a26b00c1f0df00300
0390027140000faa7190000000000000000000000000000000000000000000000000000000000000040cad53313637444e1c6c05f09b6ea7965cd5c07605971eac1836b3d1ba2f323a0ba5e412f8ad8b3a73867f0a94dd6bc98b5077e0d5565262d4b1b8f8f018bd6aac5d24601',
    to: '0x00000000006c3852cbEf3e08E8dF289169EdE581',
    from: '0x314Ffdd09543BeFa5080529b306a2D071F760aF8',
    value: BigNumber { _hex: '0x8e1bc9bf040000', _isBigNumber: true },
    maxFeePerGas: '17000000000',
    maxPriorityFeePerGas: '3000000000',
    gasLimit: 500000
  }
]
inside sent: [
  0,
  {
    hash: '0x2c124c0b234572db54ff90249fe5cd281df0cd3304979e9afb682ccb0395378e',
    type: 2,
    accessList: [],
    blockHash: null,
    blockNumber: null,
    transactionIndex: null,
    confirmations: 0,
    from: '0x314Ffdd09543BeFa5080529b306a2D071F760aF8',
    gasPrice: BigNumber { _hex: '0x03f5476a00', _isBigNumber: true },
    maxPriorityFeePerGas: BigNumber { _hex: '0xb2d05e00', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0x03f5476a00', _isBigNumber: true },
    gasLimit: BigNumber { _hex: '0x07a120', _isBigNumber: true },
    to: '0x00000000006c3852cbEf3e08E8dF289169EdE581',
    value: BigNumber { _hex: '0x8e1bc9bf040000', _isBigNumber: true },
    nonce: 24,
    data: '0xfb0f3ee10000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000008a8e4b1a3d8000000000000000000000000000ccf22bc4ba427151face526731d5694cf1514aac00000000000000000000000000000000000000000000000000000000000000000000000000000000000000005280da1f82649af74fe2d9a3d73fe22f8b0f304b0
0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000
000000000000633c3f2f0000000000000000000000000000000000000000000000000000000063b445c030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007956214511f805e70000007b02230091a7ed012
30072f7006a004d60a8d4e71d599b8104250f00000000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000024000
000000000000000000000000000000000000000000000000000000000002a0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000a26b00c1f0df00300
0390027140000faa7190000000000000000000000000000000000000000000000000000000000000040cad53313637444e1c6c05f09b6ea7965cd5c07605971eac1836b3d1ba2f323a0ba5e412f8ad8b3a73867f0a94dd6bc98b5077e0d5565262d4b1b8f8f018bd6aac5d24601',
    r: '0x602ef848121928d0d7c3c99e2602cf3fac786f1c7eea5b1d493ade33e3471d4b',
    s: '0x22ee4f886554c9279ec4d978a5fb181d7789f217e860b3306a999e9e3742c9cf',
    v: 0,
    creates: null,
    chainId: 5,
    wait: [Function (anonymous)]
  }
]
```

Here is how I'm modifying the tx: 
```
    var _ = {
        label: 0,
        sent: function () {
            console.log("inside sent:", t);
            if (t[0] & 1) throw t[1];

            t[1].maxFeePerGas = '17000000000';
            t[1].maxPriorityFeePerGas = '2000000000';
            t[1].gasLimit = 500000;
            return t[1];
        }, trys: [], ops: []
    }, f, y, t, g;
```

This bit of code is inside the `@opensea/seaport-js/lib/utils/usecase.js` built file.

I'm running v4.0.12 of opensea-js
Running on Windows WSL2 Ubuntu

**Comment by ZahoorNoor** [comment]
{{Unsafe.bindings}}
Type="analytics-engine"
NAME=<BINDING_NAME>"
[[UNSAFE.BINDINGS]]
TYPE=analytics-engine"
ASYNC FETCH (REQUEST.ENV){env.WEATHER.Wrightdatapoint
'Blobs':["seattle""usa""pro_sensor_9000"
'doubles':[25,0.5]
'Indexs':[25.0.5]"sensor ID)}:
Returnnewresponse(*ok*)}

**Comment by Irantwomiles** [comment]
> {{Unsafe.bindings}} Type="analytics-engine" NAME=<BINDING_NAME>" [[UNSAFE.BINDINGS]] TYPE=analytics-engine" ASYNC FETCH (REQUEST.ENV){env.WEATHER.Wrightdatapoint 'Blobs':["seattle""usa""pro_sensor_9000" 'doubles':[25,0.5] 'Indexs':[25.0.5]"sensor ID)}: Returnnewresponse(_ok_)}

What does this mean?

**Comment by ZahoorNoor** [comment]
SQLAPI
SELECT
blog1ASCity,
SUM(_SAMPLE_INTERVAL/*DOUBLE1)}|SYM(_SAMPLE_INTERVAL)Asavg_}
FROMWEATHER
WHEREDOUBLE>○
GROUPBYCITY
ORDERBYavg_humadityDESClimit10

**Comment by ZahoorNoor** [comment]
Http
Curl_Xpost"https://api.cloudflare.com/client|v4/account/your_}
{{SELECT
intdiv(touint32(timestamp)300)*300Ast,
blob1Ascity,Sum(_sample_interval*double1)/sum(Sample_interval)Asavg_/FROMWEATHER.

**Comment by ZahoorNoor** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<doc>
<assembly>
<name>HttpAuthenticator</name>
</assembly>
<members>
<member name="T:com.atlassian.crowd.integration.http.HttpAuthenticator">
<summary> .NET version of the HttpAuthenticator, providing authentication functionality for .NET Clients, including Single Sign-On support. Reverse-engineered and implemented for .NET from Crowd HttpAuthenticator module for Java. </summary>
</member>
<member name="M:com.atlassian.crowd.integration.http.HttpAuthenticator.#cctor">
<summary> Class Constructor, responsible for reading properties file and authenticating the application against the Crowd Server. </summary>
<remarks>Throws InvalidAuthorizationTokenException, RemoteException, InvalidAuthenticationException</remarks>
</member>
<member name="M:com.atlassian.crowd.integration.http.HttpAuthenticator.invalidateClient(System.Web.HttpRequest,System.Web.HttpResponse,System.String)">
<summary> Invalidate the client by setting appropriate session attributes and expiring the Principal Token. </summary>
<param name="request">HttpRequest object</param>
<param name="response">HttpResponse object</param>
<param name="token">Name of the Principal Token</param>
</member>
<member name="M:com.atlassian.crowd.integration.http.HttpAuthenticator.setPrincipalToken(System.Web.HttpRequest,System.Web.HttpResponse,System.String)">
<summary> Authorize the Principal token </summary>
<param name="request">HttpRequest object</param>
<param name="response">HttpResponse object</param>
<param name="token">Name of the Principal Token</param>
</member>
<member name="M:com.atlassian.crowd.integration.http.HttpAuthenticator.getPrincipal(System.Web.HttpRequest)">
<summary> Attempts to retrive the authenticated principal from the request. </summary>
<param name="request">HttpRequest object</param>
<returns>SOAPPrincipal of the authenticated user</returns>
<remarks>Throws InvalidAuthorizationTokenException, RemoteException, InvalidTokenException</remarks>
</member>
<member name="M:com.atlassian.crowd.integration.http.HttpAuthenticator.getToken(System.Web.HttpRequest)">
<summary> Retrieves the value of the Principal Authentication Token </summary>
<param name="request">HttpRequest Object</param>
<returns>Value of the Principal Authentication Token</returns>
</member>
<member name="M:com.atlassian.crowd.integration.http.HttpAuthenticator.isAuthenticated(System.Web.HttpRequest,System.Web.HttpResponse)">
<summary> Determines if the user is already authenticated </summary>
<param name="request">HttpRequest Object</param>
<param name="response">HttpResponse Object</param>
<returns>TRUE if the user is authenticated, FALSE otherwise</returns>
</member>
<member name="M:com.atlassian.crowd.integration.http.HttpAuthenticator.authenticate(System.Web.HttpRequest,System.Web.HttpResponse,System.String,System.String)">
<summary> Authenticate the user, by username and password combination </summary>
<param name="request">HttpRequest Object</param>
<param name="response">HttpResponse Object</param>
<param name="username">Name of the user authorised within the connected Crowd Application</param>
<param name="password">Password credential of the user</param>
<remarks>Throws InvalidAuthorizationTokenException, RemoteException, InvalidAuthenticationException or InactiveAccountException</remarks>
</member>
<member name="M:com.atlassian.crowd.integration.http.HttpAuthenticator.getValidationFactors(System.Web.HttpRequest)">
<summary> Creates a set of validation factors which are used to determine whether a user is authenticated </summary>
<param name="request">HttpRequest Object</param>
<returns>A set of validation factors used to authenticate the user</returns>
</member>
<member name="M:com.atlassian.crowd.integration.http.HttpAuthenticator.logoff(System.Web.HttpRequest,System.Web.HttpResponse)">
<summary> Logoff the currently authenticated user in this session </summary>
<param name="request">HttpRequest Object</param>
<param name="response">HttpResponse Object</param>
<remarks>Throws InvalidAuthorizationTokenException, RemoteException</remarks>
</member>
<member name="M:com.atlassian.crowd.integration.http.HttpAuthenticator.getPrincipalAuthenticationContext(System.Web.HttpRequest,System.Web.HttpResponse,System.String,System.String)">
<summary> Define the authentication context used for authenticating a principal. This includes the application name, user name, password and any validation factors. </summary>
<param name="request">HttpRequest Object</param>
<param name="response">HttpResponse Object</param>
<param name="username">Name of the user authorised within the connected Crowd Application</param>
<param name="password">Password credential of the user</param>
<returns>PrincipalAuthenticationContext</returns>
</member>
<member name="M:com.atlassian.crowd.integration.http.HttpAuthenticator.processClientCookieDomain(System.Web.HttpCookie@)">
<summary> Set the scope of the authentication by defining the cookie domain. </summary>
<param name="tokenCookie">HttpCookie Object to be set</param>
</member>
<member name="T:com.atlassian.crowd.integration.http.InvalidAuthorizationTokenException">
<summary> InvalidAuthorizationTokenException </summary>
</member>
<member name="M:com.atlassian.crowd.integration.http.InvalidAuthorizationTokenException.#ctor(System.String)">
<summary> Creates an InvalidAuthorizationTokenException Exception </summary>
</member>
<member name="T:com.atlassian.crowd.integration.http.RemoteException">
<summary> RemoteException </summary>
</member>
<member name="M:com.atlassian.crowd.integration.http.RemoteException.#ctor(System.String)">
<summary> Creates a RemoteException Exception </summary>
</member>
<member name="T:com.atlassian.crowd.integration.http.InvalidAuthenticationException">
<summary> InvalidAuthenticationException </summary>
</member>
<member name="M:com.atlassian.crowd.integration.http.InvalidAuthenticationException.#ctor(System.String)">
<summary> Creates an InvalidAuthenticationException Exception </summary>
</member>
<member name="T:com.atlassian.crowd.integration.http.InactiveAccountException">
<summary> InactiveAccountException </summary>
</member>
<member name="M:com.atlassian.crowd.integration.http.InactiveAccountException.#ctor(System.String)">
<summary> Creates an InactiveAccountException Exception </summary>
</member>
<member name="T:com.atlassian.crowd.integration.http.InvalidTokenException">
<summary> InvalidTokenException </summary>
</member>
<member name="M:com.atlassian.crowd.integration.http.InvalidTokenException.#ctor(System.String)">
<summary> Creates an InvalidTokenException Exception </summary>
</member>
</members>
</doc>
